services:
  laravel-backend:
    build: .
    container_name: con-laravel-backend
    volumes:
      - .:/var/www
    depends_on:
      - mysql-db
    restart: always

  nginx:
    image: nginx:latest
    container_name: con-nginx
    ports:
      - "8080:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - ../react-frontend/dist:/usr/share/nginx/html
    depends_on:
      - laravel-backend
    restart: always
  mysql-db:
    image: mysql:8.0
    container_name: con-mysql8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_backend_demo
      MYSQL_USER: laravel_app
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: